/**
 * CEQUI - Sistema de Controle de Produtividade
 * Arquivo: mock-data.js
 * Dados completos extraídos da planilha oficial (582 atividades)
 */

// ========== COLABORADORES ==========
const MOCK_COLABORADORES = [
    // role: "admin" = super usuário (acesso total), "user" = usuário comum (acesso restrito)
    // senha: definida individualmente por servidor
    { id: 1,  nome: "Alexandre Lopes Gonçalves",     ponto: 1,  area: "Mecânica",   role: "user",  senha: "cequi2026" },
    { id: 2,  nome: "Celso de Menezes Carvalho",     ponto: 2,  area: "Mecânica",   role: "user",  senha: "cequi2026" },
    { id: 3,  nome: "Dayal Machado Brito",            ponto: 3,  area: "Eletrônica", role: "user",  senha: "cequi2026" },
    { id: 4,  nome: "Diego Papa Rodrigues",           ponto: 4,  area: "Eletrônica", role: "user",  senha: "cequi2026" },
    { id: 5,  nome: "Elton Mendes de Souza",          ponto: 5,  area: "Eletrônica", role: "user",  senha: "cequi2026" },
    { id: 6,  nome: "Marcelo Macedo de Castro",       ponto: 6,  area: "Eletrônica", role: "user",  senha: "cequi2026" },
    { id: 7,  nome: "Matheus Sodré Valverde",         ponto: 7,  area: "Mecânica",   role: "user",  senha: "cequi2026" },
    { id: 8,  nome: "Murilo Borges de Lélis",         ponto: 8,  area: "Mecânica",   role: "user",  senha: "cequi2026" },
    { id: 9,  nome: "Otavio Moreira Evaristo Carlos", ponto: 9,  area: "Eletrônica", role: "user",  senha: "cequi2026" },
    { id: 10, nome: "Paulo Marques de Abreu Andrade", ponto: 10, area: "CEQUI",      role: "admin", senha: "admin2026" },
    { id: 11, nome: "Raphael Queiroz Gomes",          ponto: 11, area: "Mecânica",   role: "user",  senha: "cequi2026" }
];

// ========== CATEGORIAS ==========
const CATEGORIAS = {
    DGS:   { nome: "Direção, Gestão e Supervisão",    icone: "📋" },
    OPMN:  { nome: "Operação e Manutenção",           icone: "🔧" },
    PROJ:  { nome: "Projetos",                         icone: "📐" },
    ESPEC: { nome: "Especificações",                   icone: "📝" },
    FISC:  { nome: "Fiscalização e Execução",          icone: "🔍" },
    LIVRE: { nome: "Atividades Livres",                icone: ""   }
};

// Prefixo real dos códigos por categoria (usado em gerarProximoCodigo)
const CATEGORIA_PREFIX = {
    DGS:   'DGS',
    OPMN:  'OEM',
    PROJ:  'PROJ',
    ESPEC: 'ESP',
    FISC:  'FISCEXEC'
};

// Esperança de Média Diária por área (benchmark oficial da planilha)
const BENCHMARK_AREA = {
    "Mecânica":   8,
    "Eletrônica": 8,
    "CEQUI":      8
};

// Mapeamento: área do servidor → categorias de atividades disponíveis
const AREA_CATEGORIAS = {
    "Mecânica":   ["DGS", "OPMN", "PROJ", "ESPEC", "FISC"],
    "Eletrônica": ["DGS", "OPMN", "PROJ", "ESPEC", "FISC"],
    "CEQUI":      ["DGS", "OPMN", "PROJ", "ESPEC", "FISC"]
};
// Valores válidos de complexidade (multiplicador)
const COMPLEXIDADES = [0.5, 1, 1.5];

// ========== 582 ATIVIDADES PADRÃO ==========
const MOCK_ATIVIDADES = {
    DGS: [
        { id: 1, codigo: "DGS01", atividade: "Análise e instrução de demandas - Elaboração de análise, revisão e ajuste de projetos e especificações (baixa complexidade)", peso: 2, categoria: "DGS" },
        { id: 2, codigo: "DGS02", atividade: "Análise e instrução de demandas - Elaboração de análise, revisão e ajuste de projetos e especificações (média complexidade)", peso: 4, categoria: "DGS" },
        { id: 3, codigo: "DGS03", atividade: "Análise e instrução de demandas - Elaboração de análise, revisão e ajuste de projetos e especificações (alta complexidade)", peso: 8, categoria: "DGS" },
        { id: 4, codigo: "DGS04", atividade: "Análise e instrução de demandas - Elaboração de despachos, instruções e decisões (baixa complexidade)", peso: 4, categoria: "DGS" },
        { id: 5, codigo: "DGS05", atividade: "Análise e instrução de demandas - Elaboração de despachos, instruções e decisões (média complexidade)", peso: 6, categoria: "DGS" },
        { id: 6, codigo: "DGS06", atividade: "Análise e instrução de demandas - Elaboração de despachos, instruções e decisões (alta complexidade)", peso: 8, categoria: "DGS" },
        { id: 7, codigo: "DGS07", atividade: "Análise e instrução de demandas - Recebimento de demandas e levantamento de ações iniciais", peso: 2, categoria: "DGS" },
        { id: 8, codigo: "DGS08", atividade: "Análise e instrução de demandas - Triagem, classificação e priorização de demandas", peso: 2, categoria: "DGS" },
        { id: 9, codigo: "DGS09", atividade: "Apoio logístico – Elaboração de diligência para solicitar apoio logístico", peso: 2, categoria: "DGS" },
        { id: 10, codigo: "DGS10", atividade: "Elaboração de parecer técnico fundamentado (baixa complexidade)", peso: 8, categoria: "DGS" },
        { id: 11, codigo: "DGS11", atividade: "Elaboração de parecer técnico fundamentado (média complexidade)", peso: 14, categoria: "DGS" },
        { id: 12, codigo: "DGS12", atividade: "Elaboração de parecer técnico fundamentado (alta complexidade)", peso: 20, categoria: "DGS" },
        { id: 13, codigo: "DGS13", atividade: "Emissão de subsídios técnicos - Processos de fiscalização ou contratação de obras e serviços de engenharia", peso: 20, categoria: "DGS" },
        { id: 14, codigo: "DGS14", atividade: "Emissão de subsídios técnicos - Processos ordinários", peso: 4, categoria: "DGS" },
        { id: 15, codigo: "DGS15", atividade: "Gestão Organizacional - Aferição e consolidação de indicadores de produtividade da equipe terceirizada", peso: 6, categoria: "DGS" },
        { id: 16, codigo: "DGS16", atividade: "Gestão Organizacional - Aferição e consolidação de indicadores de produtividade de equipe própria", peso: 6, categoria: "DGS" },
        { id: 17, codigo: "DGS17", atividade: "Gestão Organizacional - Catalogação, indexação e controle de documentos para o acervo da unidade", peso: 4, categoria: "DGS" },
        { id: 18, codigo: "DGS18", atividade: "Gestão Organizacional - Desenvolvimento e implementação de ferramentas e soluções tecnológicas", peso: 16, categoria: "DGS" },
        { id: 19, codigo: "DGS19", atividade: "Gestão Organizacional - Elaboração de ajuste ou correção de processo de trabalho da coordenação ou da área temática", peso: 6, categoria: "DGS" },
        { id: 20, codigo: "DGS20", atividade: "Gestão Organizacional - Elaboração de ajuste ou correção no acompanhamento semanal de entregas de produtos", peso: 4, categoria: "DGS" },
        { id: 21, codigo: "DGS21", atividade: "Gestão Organizacional - Elaboração de controles internos", peso: 8, categoria: "DGS" },
        { id: 22, codigo: "DGS22", atividade: "Gestão Organizacional - Elaboração de diagnóstico de processo de trabalho da coordenação ou da área temática", peso: 6, categoria: "DGS" },
        { id: 23, codigo: "DGS23", atividade: "Gestão Organizacional - Elaboração e acompanhamento do planejamento mensal de entregas e produtos dos servidores", peso: 8, categoria: "DGS" },
        { id: 24, codigo: "DGS24", atividade: "Gestão Organizacional - Elaboração manual técnico", peso: 8, categoria: "DGS" },
        { id: 25, codigo: "DGS25", atividade: "Gestão Patrimonial - Instrução de processos de movimentação, de baixa ou de manutenção patrimonial", peso: 2, categoria: "DGS" },
        { id: 26, codigo: "DGS26", atividade: "Gestão Patrimonial - Realização de inventário periódico e conferência de bens patrimoniais", peso: 8, categoria: "DGS" },
        { id: 27, codigo: "DGS27", atividade: "Plano de Compras Anual – Consolidação e validação", peso: 6, categoria: "DGS" },
        { id: 28, codigo: "DGS28", atividade: "Plano de Compras Anual – Instrução de diligência para a etapa de análise de DFDs", peso: 4, categoria: "DGS" },
        { id: 29, codigo: "DGS29", atividade: "Plano de Compras Anual – Instrução de diligência para a etapa interna de elaboração", peso: 6, categoria: "DGS" },
        { id: 30, codigo: "DGS30", atividade: "Plano de Compras Anual – Instrução de diligência para ajuste e acompanhamento das ações", peso: 4, categoria: "DGS" },
        { id: 31, codigo: "DGS31", atividade: "Proposta orçamentária – Elaboração da proposta orçamentária anual da Coordenação", peso: 4, categoria: "DGS" },
        { id: 32, codigo: "DGS32", atividade: "Proposta orçamentária – Fornecer informações para elaboração de relatório de execução orçamentária e de obras eletivas", peso: 4, categoria: "DGS" },
        { id: 33, codigo: "DGS33", atividade: "Proposta orçamentária – Reprogramação dos saldos anuais de execução orçamentária", peso: 4, categoria: "DGS" },
        { id: 34, codigo: "DGS34", atividade: "Gestão do PDP – Elaboração de relatório periódico de execução", peso: 4, categoria: "DGS" },
        { id: 35, codigo: "DGS35", atividade: "Gestão do PDP – Execução de ações de capacitação em sistemas e equipamentos de alta complexidade", peso: 40, categoria: "DGS" },
        { id: 36, codigo: "DGS36", atividade: "Gestão do PDP – Execução de ações de capacitação em sistemas e equipamentos de baixa complexidade", peso: 8, categoria: "DGS" },
        { id: 37, codigo: "DGS37", atividade: "Gestão do PDP – Execução de ações de capacitação em sistemas e equipamentos de média complexidade", peso: 20, categoria: "DGS" }
    ],
    OPMN: [
        { id: 1, codigo: "OEM01", atividade: "Operação e manutenção - Elaboração do plano de operação, manutenção e controle semanal", peso: 4, categoria: "OPMN" },
        { id: 2, codigo: "OEM02", atividade: "Operação e manutenção - Elaboração de correção ou ajuste no plano de manutenção semanal", peso: 2, categoria: "OPMN" },
        { id: 3, codigo: "OEM03", atividade: "Operação e manutenção - Elaboração, registro e acompanhamento do plano de fiscalização contratual semanal", peso: 4, categoria: "OPMN" },
        { id: 4, codigo: "OEM04", atividade: "Operação e manutenção - Elaboração de documentação para medição de serviços de operação e manutenção", peso: 4, categoria: "OPMN" },
        { id: 5, codigo: "OEM05", atividade: "Operação e manutenção - Elaboração de parecer sobre orçamentos para aquisição de peças e equipamentos (baixa complexidade)", peso: 4, categoria: "OPMN" },
        { id: 6, codigo: "OEM06", atividade: "Operação e manutenção – Elaboração de parecer sobre orçamentos para aquisição de peças e equipamentos (média complexidade)", peso: 6, categoria: "OPMN" },
        { id: 7, codigo: "OEM07", atividade: "Operação e manutenção – Elaboração de parecer sobre orçamentos para aquisição de peças e equipamentos (alta complexidade)", peso: 8, categoria: "OPMN" },
        { id: 8, codigo: "OEM08", atividade: "Operação e manutenção - Elaboração de parecer sobre relatórios técnicos de operação e manutenção", peso: 2, categoria: "OPMN" },
        { id: 9, codigo: "OEM09", atividade: "Operação e manutenção - Elaboração de parecer sobre solicitações de usuários acerca de operação ou manutenção de equipamentos", peso: 2, categoria: "OPMN" },
        { id: 10, codigo: "OEM10", atividade: "Operação e manutenção - Emissão de subsídios técnicos em processos ou ações de operação ou manutenção", peso: 2, categoria: "OPMN" },
        { id: 11, codigo: "OEM11", atividade: "Operação e manutenção - Execução de ações de Inspeção, avaliação, coleta de dados, configuração, programação em equipamentos e instalações (baixa complexidade)", peso: 2, categoria: "OPMN" },
        { id: 12, codigo: "OEM12", atividade: "Operação e manutenção - Execução de ações de Inspeção, avaliação, coleta de dados, configuração, programação em equipamentos e instalações (média complexidade)", peso: 4, categoria: "OPMN" },
        { id: 13, codigo: "OEM13", atividade: "Operação e manutenção - Execução de ações de Inspeção, avaliação, coleta de dados, configuração, programação em equipamentos e instalações (alta complexidade)", peso: 8, categoria: "OPMN" },
        { id: 14, codigo: "OEM14", atividade: "Operação e manutenção - Execução de ações para recebimento de materiais ou serviços relativos a serviços de operação e manutenção (baixa complexidade)", peso: 2, categoria: "OPMN" },
        { id: 15, codigo: "OEM15", atividade: "Operação e manutenção - Execução de ações para recebimento de materiais ou serviços relativos a serviços de operação e manutenção (média complexidade)", peso: 4, categoria: "OPMN" },
        { id: 16, codigo: "OEM16", atividade: "Operação e manutenção - Execução de ações para recebimento de materiais ou serviços relativos a serviços de operação e manutenção (alta complexidade)", peso: 8, categoria: "OPMN" },
        { id: 17, codigo: "OEM17", atividade: "Operação e manutenção - Levantamento e análise de dados estatísticos relativos aos equipamentos e sistemas (baixa complexidade)", peso: 2, categoria: "OPMN" },
        { id: 18, codigo: "OEM18", atividade: "Operação e manutenção - Levantamento e análise de dados estatísticos relativos aos equipamentos e sistemas (média complexidade)", peso: 4, categoria: "OPMN" },
        { id: 19, codigo: "OEM19", atividade: "Operação e manutenção - Levantamento e análise de dados estatísticos relativos aos equipamentos e sistemas (alta complexidade)", peso: 8, categoria: "OPMN" },
        { id: 20, codigo: "OEM20", atividade: "Operação e manutenção de automação –  Elaboração de parecer sobre relatórios técnicos de desempenho de sistemas de automação e supervisão predial", peso: 2, categoria: "OPMN" },
        { id: 21, codigo: "OEM21", atividade: "Operação e manutenção de automação –  Execução de ações de inspeção, avaliação, configuração, programação e coleta de dados em centrais de automação, quadros de comando, servidores e redes (baixa complexidade)", peso: 2, categoria: "OPMN" },
        { id: 22, codigo: "OEM22", atividade: "Operação e manutenção de automação –  Execução de ações de inspeção, avaliação, configuração, programação e coleta de dados em centrais de automação, quadros de comando, servidores e redes (média complexidade)", peso: 4, categoria: "OPMN" },
        { id: 23, codigo: "OEM23", atividade: "Operação e manutenção de automação –  Execução de ações de inspeção, avaliação, configuração, programação e coleta de dados em centrais de automação, quadros de comando, servidores e redes (alta complexidade)", peso: 8, categoria: "OPMN" },
        { id: 24, codigo: "OEM24", atividade: "Especificação de materiais, equipamentos e serviços para operação e manutenção - análise e revisão das especificações técnicas atuais (baixa complexidade)", peso: 8, categoria: "OPMN" },
        { id: 25, codigo: "OEM25", atividade: "Especificação de materiais, equipamentos e serviços para operação e manutenção - análise e revisão das especificações técnicas atuais (média complexidade)", peso: 12, categoria: "OPMN" },
        { id: 26, codigo: "OEM26", atividade: "Especificação de materiais, equipamentos e serviços para operação e manutenção - análise e revisão das especificações técnicas atuais (alta complexidade)", peso: 20, categoria: "OPMN" },
        { id: 27, codigo: "OEM27", atividade: "Especificações para operação e manutenção - Avaliação e emissão de parecer sobre o orçamento", peso: 4, categoria: "OPMN" },
        { id: 28, codigo: "OEM28", atividade: "Especificações para operação e manutenção - Elaboração de caderno de especificações para aquisição de materiais, equipamentos e serviços para operação e manutenção", peso: 20, categoria: "OPMN" },
        { id: 29, codigo: "OEM29", atividade: "Especificações para operação e manutenção - Elaboração de estudo técnico preliminar para aquisição de materiais, equipamentos e serviços para operação e manutenção", peso: 8, categoria: "OPMN" },
        { id: 30, codigo: "OEM30", atividade: "Especificações para operação e manutenção - Elaboração de mapa de risco para contratações de serviços", peso: 12, categoria: "OPMN" },
        { id: 31, codigo: "OEM31", atividade: "Especificações para operação e manutenção - Elaboração de termo de referência para aquisição de materiais, equipamentos e serviços para operação e manutenção", peso: 12, categoria: "OPMN" },
        { id: 32, codigo: "OEM32", atividade: "Especificação de materiais, equipamentos e serviços para operação e manutenção - realização de pesquisa de mercado e contato com fornecedores", peso: 8, categoria: "OPMN" },
        { id: 33, codigo: "OEM33", atividade: "Especificação de materiais, equipamentos e serviços para operação e manutenção - seleção de características dos itens", peso: 8, categoria: "OPMN" },
        { id: 34, codigo: "OEM34", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - análise de especificações atuais", peso: 20, categoria: "OPMN" },
        { id: 35, codigo: "OEM35", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - Avaliação e emissão de parecer sobre o orçamento", peso: 4, categoria: "OPMN" },
        { id: 36, codigo: "OEM36", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - dimensionamento de mão de obra", peso: 20, categoria: "OPMN" },
        { id: 37, codigo: "OEM37", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - dimensionamento de rotinas de manutenção", peso: 16, categoria: "OPMN" },
        { id: 38, codigo: "OEM38", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - dimensionamento e especificação de EPIs/EPCs", peso: 20, categoria: "OPMN" },
        { id: 39, codigo: "OEM39", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - dimensionamento e especificação de ferramental", peso: 20, categoria: "OPMN" },
        { id: 40, codigo: "OEM40", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - dimensionamento e especificação de materiais sob demanda", peso: 20, categoria: "OPMN" },
        { id: 41, codigo: "OEM41", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - dimensionamento e especificação de serviços especializados continuados", peso: 20, categoria: "OPMN" },
        { id: 42, codigo: "OEM42", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - dimensionamento e especificação de serviços sob demanda", peso: 20, categoria: "OPMN" },
        { id: 43, codigo: "OEM43", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - elaboração de documentação para comprovação de requisitos de habilitação técnica", peso: 20, categoria: "OPMN" },
        { id: 44, codigo: "OEM44", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - elaboração de planilhas para composição de materiais e serviços", peso: 20, categoria: "OPMN" },
        { id: 45, codigo: "OEM45", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - elaboração do caderno de especificações técnicas", peso: 20, categoria: "OPMN" },
        { id: 46, codigo: "OEM46", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - elaboração do mapa de riscos", peso: 20, categoria: "OPMN" },
        { id: 47, codigo: "OEM47", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - elaboração do termo de referência", peso: 20, categoria: "OPMN" },
        { id: 48, codigo: "OEM48", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - especificação de serviços de análise da qualidade do ar interior", peso: 20, categoria: "OPMN" },
        { id: 49, codigo: "OEM49", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - especificação de serviços de tratamento químico da água", peso: 20, categoria: "OPMN" },
        { id: 50, codigo: "OEM50", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada - levantamento dos equipamentos e sistemas instalados", peso: 20, categoria: "OPMN" },
        { id: 51, codigo: "OEM51", atividade: "Especificação para contratação de serviços de operação e manutenção terceirizada -especificação de serviços de manutenção preventiva e corretiva para unidades resfriadoras de líquido", peso: 20, categoria: "OPMN" }
    ],
    PROJ: [
        { id: 1, codigo: "PROJ01", atividade: "Elaboração de projetos de engenharia - Avaliação e emissão de parecer sobre o orçamento (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 2, codigo: "PROJ02", atividade: "Elaboração de projetos de engenharia -  Avaliação e emissão de parecer sobre o orçamento (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 3, codigo: "PROJ03", atividade: "Elaboração de projetos de engenharia - Avaliação e emissão de parecer sobre o orçamento (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 4, codigo: "PROJ04", atividade: "Elaboração de projetos de engenharia - Elaboração de anteprojeto (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 5, codigo: "PROJ05", atividade: "Elaboração de projetos de engenharia - Elaboração de anteprojeto (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 6, codigo: "PROJ06", atividade: "Elaboração de projetos de engenharia - Elaboração de anteprojeto (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 7, codigo: "PROJ07", atividade: "Elaboração de projetos de engenharia - Elaboração de caderno de especificações técnicas (baixa complexidade)", peso: 8, categoria: "PROJ" },
        { id: 8, codigo: "PROJ08", atividade: "Elaboração de projetos de engenharia - Elaboração de caderno de especificações técnicas (média complexidade)", peso: 12, categoria: "PROJ" },
        { id: 9, codigo: "PROJ09", atividade: "Elaboração de projetos de engenharia - Elaboração de caderno de especificações técnicas (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 10, codigo: "PROJ10", atividade: "Elaboração de projetos de engenharia - Elaboração de desenhos técnicos (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 11, codigo: "PROJ11", atividade: "Elaboração de projetos de engenharia - Elaboração de desenhos técnicos (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 12, codigo: "PROJ12", atividade: "Elaboração de projetos de engenharia - Elaboração de desenhos técnicos (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 13, codigo: "PROJ13", atividade: "Elaboração de projetos de engenharia - Elaboração de estudo de viabilidade técnica e econômica de engenharia (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 14, codigo: "PROJ14", atividade: "Elaboração de projetos de engenharia - Elaboração de estudo de viabilidade técnica e econômica de engenharia (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 15, codigo: "PROJ15", atividade: "Elaboração de projetos de engenharia - Elaboração de estudo de viabilidade técnica e econômica de engenharia (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 16, codigo: "PROJ16", atividade: "Elaboração de projetos de engenharia - Elaboração de formulário de ETP (baixa complexidade)", peso: 8, categoria: "PROJ" },
        { id: 17, codigo: "PROJ17", atividade: "Elaboração de projetos de engenharia - Elaboração de formulário de ETP (média complexidade)", peso: 12, categoria: "PROJ" },
        { id: 18, codigo: "PROJ18", atividade: "Elaboração de projetos de engenharia - Elaboração de formulário de ETP (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 19, codigo: "PROJ19", atividade: "Elaboração de projetos de engenharia - Elaboração de planilha de composição de materiais e serviços (baixa complexidade)", peso: 8, categoria: "PROJ" },
        { id: 20, codigo: "PROJ20", atividade: "Elaboração de projetos de engenharia - Elaboração de planilha de composição de materiais e serviços (média complexidade)", peso: 12, categoria: "PROJ" },
        { id: 21, codigo: "PROJ21", atividade: "Elaboração de projetos de engenharia - Elaboração de planilha de composição de materiais e serviços (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 22, codigo: "PROJ22", atividade: "Elaboração de projetos de engenharia - Elaboração de projeto básico (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 23, codigo: "PROJ23", atividade: "Elaboração de projetos de engenharia - Elaboração de projeto básico (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 24, codigo: "PROJ24", atividade: "Elaboração de projetos de engenharia - Elaboração de projeto básico (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 25, codigo: "PROJ25", atividade: "Elaboração de projetos de engenharia - Elaboração de projeto executivo (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 26, codigo: "PROJ26", atividade: "Elaboração de projetos de engenharia - Elaboração de projeto executivo (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 27, codigo: "PROJ27", atividade: "Elaboração de projetos de engenharia - Elaboração de projeto executivo (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 28, codigo: "PROJ28", atividade: "Elaboração de projetos de engenharia - Elaboração de requisitos técnicos (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 29, codigo: "PROJ29", atividade: "Elaboração de projetos de engenharia - Elaboração de requisitos técnicos (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 30, codigo: "PROJ30", atividade: "Elaboração de projetos de engenharia - Elaboração de requisitos técnicos (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 31, codigo: "PROJ31", atividade: "Elaboração de projetos de engenharia - Elaboração de termo de referência (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 32, codigo: "PROJ32", atividade: "Elaboração de projetos de engenharia - Elaboração de termo de referência (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 33, codigo: "PROJ33", atividade: "Elaboração de projetos de engenharia - Elaboração de termo de referência (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 34, codigo: "PROJ34", atividade: "Elaboração de projetos de engenharia - Levantamento de informações e vistorias in loco (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 35, codigo: "PROJ35", atividade: "Elaboração de projetos de engenharia - Levantamento de informações e vistorias in loco (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 36, codigo: "PROJ36", atividade: "Elaboração de projetos de engenharia - Levantamento de informações e vistorias in loco (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 37, codigo: "PROJ37", atividade: "Elaboração de projetos de engenharia - Levantamento e análise de projetos existentes (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 38, codigo: "PROJ38", atividade: "Elaboração de projetos de engenharia - Levantamento e análise de projetos existentes (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 39, codigo: "PROJ39", atividade: "Elaboração de projetos de engenharia - Levantamento e análise de projetos existentes (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 40, codigo: "PROJ40", atividade: "Elaboração de projetos de engenharia - Elaboração de mapa de risco", peso: 12, categoria: "PROJ" },
        { id: 41, codigo: "PROJ41", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos de automação - análise e revisão das especificações técnicas atuais (baixa complexidade)", peso: 2, categoria: "PROJ" },
        { id: 42, codigo: "PROJ42", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos de automação - análise e revisão das especificações técnicas atuais (média complexidade)", peso: 4, categoria: "PROJ" },
        { id: 43, codigo: "PROJ43", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos de automação - análise e revisão das especificações técnicas atuais (alta complexidade)", peso: 8, categoria: "PROJ" },
        { id: 44, codigo: "PROJ44", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos de automação - realização de pesquisa de mercado e contato com fornecedores", peso: 8, categoria: "PROJ" },
        { id: 45, codigo: "PROJ45", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos de automação - seleção de características dos itens", peso: 8, categoria: "PROJ" },
        { id: 46, codigo: "PROJ46", atividade: "Produção técnica especializada - Elaboração de apresentação técnica (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 47, codigo: "PROJ47", atividade: "Produção técnica especializada - Elaboração de apresentação técnica (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 48, codigo: "PROJ48", atividade: "Produção técnica especializada - Elaboração de apresentação técnica (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 49, codigo: "PROJ49", atividade: "Produção técnica especializada - Elaboração de estudo técnico (comparativo, prospectivo ou simulação) (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 50, codigo: "PROJ50", atividade: "Produção técnica especializada - Elaboração de estudo técnico (comparativo, prospectivo ou simulação) (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 51, codigo: "PROJ51", atividade: "Produção técnica especializada - Elaboração de laudo de conformidade/eficiência de equipamentos e sistemas (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 52, codigo: "PROJ52", atividade: "Produção técnica especializada - Elaboração de laudo de conformidade/eficiência de equipamentos e sistemas (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 53, codigo: "PROJ53", atividade: "Produção técnica especializada - Elaboração de laudo de conformidade/eficiência de equipamentos e sistemas (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 54, codigo: "PROJ54", atividade: "Produção técnica especializada - Elaboração de estudo técnico (comparativo, prospectivo ou simulação) (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 55, codigo: "PROJ55", atividade: "Produção técnica especializada - Elaboração de manual para treinamento técnico especializado (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 56, codigo: "PROJ56", atividade: "Produção técnica especializada - Elaboração de manual para treinamento técnico especializado (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 57, codigo: "PROJ57", atividade: "Produção técnica especializada - Elaboração de manual para treinamento técnico especializado (alta complexidade)", peso: 20, categoria: "PROJ" },
        { id: 58, codigo: "PROJ58", atividade: "Produção técnica especializada - Elaboração de parecer técnico sobre equipamentos e sistemas (baixa complexidade)", peso: 4, categoria: "PROJ" },
        { id: 59, codigo: "PROJ59", atividade: "Produção técnica especializada - Elaboração de parecer técnico sobre equipamentos e sistemas (média complexidade)", peso: 8, categoria: "PROJ" },
        { id: 60, codigo: "PROJ60", atividade: "Produção técnica especializada - Elaboração de parecer técnico sobre equipamentos e sistemas (alta complexidade)", peso: 20, categoria: "PROJ" }
    ],
    ESPEC: [
        { id: 1, codigo: "ESP01", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - análise e revisão das especificações técnicas atuais (baixa complexidade)", peso: 8, categoria: "ESPEC" },
        { id: 2, codigo: "ESP02", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - análise e revisão das especificações técnicas atuais (média complexidade)", peso: 12, categoria: "ESPEC" },
        { id: 3, codigo: "ESP03", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - análise e revisão das especificações técnicas atuais (alta complexidade)", peso: 20, categoria: "ESPEC" },
        { id: 4, codigo: "ESP04", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - seleção de características dos itens (baixa complexidade)", peso: 4, categoria: "ESPEC" },
        { id: 5, codigo: "ESP05", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - seleção de características dos itens (média complexidade)", peso: 12, categoria: "ESPEC" },
        { id: 6, codigo: "ESP06", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - seleção de características dos itens (alta complexidade)", peso: 20, categoria: "ESPEC" },
        { id: 7, codigo: "ESP07", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - realização de pesquisa de mercado e contato com fornecedores (baixa complexidade)", peso: 4, categoria: "ESPEC" },
        { id: 8, codigo: "ESP08", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - realização de pesquisa de mercado e contato com fornecedores (média complexidade)", peso: 12, categoria: "ESPEC" },
        { id: 9, codigo: "ESP09", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - realização de pesquisa de mercado e contato com fornecedores (alta complexidade)", peso: 20, categoria: "ESPEC" },
        { id: 10, codigo: "ESP10", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de estudo técnico preliminar (baixa complexidade)", peso: 8, categoria: "ESPEC" },
        { id: 11, codigo: "ESP11", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de estudo técnico preliminar (média complexidade)", peso: 12, categoria: "ESPEC" },
        { id: 12, codigo: "ESP12", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de estudo técnico preliminar (alta complexidade)", peso: 20, categoria: "ESPEC" },
        { id: 13, codigo: "ESP13", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de termo de referência (baixa complexidade)", peso: 8, categoria: "ESPEC" },
        { id: 14, codigo: "ESP14", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de termo de referência (média complexidade)", peso: 12, categoria: "ESPEC" },
        { id: 15, codigo: "ESP15", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de termo de referência (alta complexidade)", peso: 20, categoria: "ESPEC" },
        { id: 16, codigo: "ESP16", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de caderno de especificações (baixa complexidade)", peso: 8, categoria: "ESPEC" },
        { id: 17, codigo: "ESP17", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de caderno de especificações (média complexidade)", peso: 12, categoria: "ESPEC" },
        { id: 18, codigo: "ESP18", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de caderno de especificações (alta complexidade)", peso: 20, categoria: "ESPEC" },
        { id: 19, codigo: "ESP19", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de mapa de risco (baixa complexidade)", peso: 8, categoria: "ESPEC" },
        { id: 20, codigo: "ESP20", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de mapa de risco (média complexidade)", peso: 12, categoria: "ESPEC" },
        { id: 21, codigo: "ESP21", atividade: "Especificação para contratação de fornecimento e instalação de equipamentos - Elaboração de mapa de risco (alta complexidade)", peso: 20, categoria: "ESPEC" },
        { id: 22, codigo: "ESP22", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - levantamento dos equipamentos e sistemas instalados (baixa complexidade)", peso: 4, categoria: "ESPEC" },
        { id: 23, codigo: "ESP23", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - levantamento dos equipamentos e sistemas instalados (alta complexidade)", peso: 20, categoria: "ESPEC" },
        { id: 24, codigo: "ESP24", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - análise de especificações atuais (baixa complexidade)", peso: 4, categoria: "ESPEC" },
        { id: 25, codigo: "ESP25", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - análise de especificações atuais (alta complexidade)", peso: 20, categoria: "ESPEC" },
        { id: 26, codigo: "ESP26", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - dimensionamento de rotinas de manutenção", peso: 8, categoria: "ESPEC" },
        { id: 27, codigo: "ESP27", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - dimensionamento e especificação de materiais sob demanda", peso: 8, categoria: "ESPEC" },
        { id: 28, codigo: "ESP28", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - dimensionamento e especificação de serviços sob demanda", peso: 8, categoria: "ESPEC" },
        { id: 29, codigo: "ESP29", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - elaboração de documentação para comprovação de requisitos de habilitação técnica", peso: 8, categoria: "ESPEC" },
        { id: 30, codigo: "ESP30", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - elaboração de estudo técnico preliminar", peso: 8, categoria: "ESPEC" },
        { id: 31, codigo: "ESP31", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - elaboração de planilhas para composição de materiais e serviços", peso: 8, categoria: "ESPEC" },
        { id: 32, codigo: "ESP32", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - elaboração do caderno de especificações técnicas", peso: 8, categoria: "ESPEC" },
        { id: 33, codigo: "ESP33", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - elaboração do mapa de riscos", peso: 8, categoria: "ESPEC" },
        { id: 34, codigo: "ESP34", atividade: "Especificação para contratação de serviços de operação e manutenção de equipamentos - elaboração do termo de referência", peso: 4, categoria: "ESPEC" },
        { id: 35, codigo: "ESP35", atividade: "Especificações - Avaliação e emissão de parecer sobre o orçamento", peso: 4, categoria: "ESPEC" }
    ],
    FISC: [
        { id: 1, codigo: "FISCEXEC01", atividade: "Fiscalização - análise de projeto contratado com emissão de parecer, por prancha (baixa complexidade)", peso: 8, categoria: "FISC" },
        { id: 2, codigo: "FISCEXEC02", atividade: "Fiscalização - análise de projeto contratado com emissão de parecer, por prancha (média complexidade)", peso: 12, categoria: "FISC" },
        { id: 3, codigo: "FISCEXEC03", atividade: "Fiscalização - análise de projeto contratado com emissão de parecer, por prancha (alta complexidade)", peso: 20, categoria: "FISC" },
        { id: 4, codigo: "FISCEXEC04", atividade: "Fiscalização - Elaboração do plano de fiscalização", peso: 12, categoria: "FISC" },
        { id: 5, codigo: "FISCEXEC05", atividade: "Fiscalização - Elaboração do cronograma de execução", peso: 20, categoria: "FISC" },
        { id: 6, codigo: "FISCEXEC06", atividade: "Fiscalização - Elaboração de ajuste, correção e registro do plano de fiscalização semanal", peso: 4, categoria: "FISC" },
        { id: 7, codigo: "FISCEXEC07", atividade: "Fiscalização - Estudo de documentação do contrato", peso: 20, categoria: "FISC" },
        { id: 8, codigo: "FISCEXEC08", atividade: "Fiscalização - Elaboração de documentação para medição (baixa complexidade)", peso: 4, categoria: "FISC" },
        { id: 9, codigo: "FISCEXEC09", atividade: "Fiscalização - Elaboração de documentação para medição (média complexidade)", peso: 8, categoria: "FISC" },
        { id: 10, codigo: "FISCEXEC10", atividade: "Fiscalização - Elaboração de documentação para medição (alta complexidade)", peso: 20, categoria: "FISC" },
        { id: 11, codigo: "FISCEXEC11", atividade: "Fiscalização - Elaboração de instrução processual para alteração contratual (baixa complexidade)", peso: 4, categoria: "FISC" },
        { id: 12, codigo: "FISCEXEC12", atividade: "Fiscalização - Elaboração de instrução processual para alteração contratual (média complexidade)", peso: 12, categoria: "FISC" },
        { id: 13, codigo: "FISCEXEC13", atividade: "Fiscalização - Elaboração de instrução processual para alteração contratual (alta complexidade)", peso: 20, categoria: "FISC" },
        { id: 14, codigo: "FISCEXEC14", atividade: "Fiscalização - Elaboração de instrução processual para aplicação de sanções ou multas", peso: 8, categoria: "FISC" },
        { id: 15, codigo: "FISCEXEC15", atividade: "Fiscalização - Elaboração de parecer acerca da documentação de entrega da obra (as built, manuais, relatórios)", peso: 16, categoria: "FISC" },
        { id: 16, codigo: "FISCEXEC16", atividade: "Fiscalização - Elaboração de relatório de acompanhamento de obra (baixa complexidade)", peso: 2, categoria: "FISC" },
        { id: 17, codigo: "FISCEXEC17", atividade: "Fiscalização - Elaboração de relatório de acompanhamento de obra (média complexidade)", peso: 4, categoria: "FISC" },
        { id: 18, codigo: "FISCEXEC18", atividade: "Fiscalização - Elaboração de relatório de acompanhamento de obra (alta complexidade)", peso: 8, categoria: "FISC" },
        { id: 19, codigo: "FISCEXEC19", atividade: "Fiscalização - Execução de ações para análise de equivalência técnica ou recebimento de materiais ou serviços (baixa complexidade)", peso: 2, categoria: "FISC" },
        { id: 20, codigo: "FISCEXEC20", atividade: "Fiscalização - Execução de ações para análise de equivalência técnica ou recebimento de materiais ou serviços (média complexidade)", peso: 4, categoria: "FISC" },
        { id: 21, codigo: "FISCEXEC21", atividade: "Fiscalização - Execução de ações para análise de equivalência técnica ou recebimento de materiais ou serviços (alta complexidade)", peso: 8, categoria: "FISC" },
        { id: 22, codigo: "FISCEXEC22", atividade: "Fiscalização - Realização de vistoria para avaliação, atualização de projeto e coordenação de serviços (baixa complexidade)", peso: 2, categoria: "FISC" },
        { id: 23, codigo: "FISCEXEC23", atividade: "Fiscalização - Realização de vistoria para avaliação, atualização de projeto e coordenação de serviços (média complexidade)", peso: 8, categoria: "FISC" },
        { id: 24, codigo: "FISCEXEC24", atividade: "Fiscalização - Realização de vistoria para avaliação, atualização de projeto e coordenação de serviços (alta complexidade)", peso: 20, categoria: "FISC" },
        { id: 25, codigo: "FISCEXEC25", atividade: "Fiscalização - Realização de inspeção, vistoria e elaboração de documentação para recebimento da obra", peso: 20, categoria: "FISC" },
        { id: 26, codigo: "FISCEXEC26", atividade: "Fiscalização - Elaboração de ajuste ou documentação para controle financeiro de contrato, por contrato", peso: 4, categoria: "FISC" },
        { id: 27, codigo: "FISCEXEC27", atividade: "Fiscalização - Emissão de subsídios técnicos em fiscalização", peso: 2, categoria: "FISC" },
        { id: 28, codigo: "FISCEXEC28", atividade: "Execução direta - Realização de vistoria para coordenação dos serviços in loco", peso: 4, categoria: "FISC" },
        { id: 29, codigo: "FISCEXEC29", atividade: "Execução direta - Elaboração de lista de materiais e serviços necessários à execução", peso: 4, categoria: "FISC" },
        { id: 30, codigo: "FISCEXEC30", atividade: "Execução direta - Elaboração de orçamento para estimativa de custos de execuções", peso: 4, categoria: "FISC" },
        { id: 31, codigo: "FISCEXEC31", atividade: "Execução direta - Elaboração de planejamento e cronograma de obras", peso: 4, categoria: "FISC" },
        { id: 32, codigo: "FISCEXEC32", atividade: "Execução direta - Elaboração de relatório de apropriação de custos de serviço de execução direta", peso: 4, categoria: "FISC" },
        { id: 33, codigo: "FISCEXEC33", atividade: "Execução direta - Montagem ou atualização de quadro de comando de sistema de automação (baixa complexidade)", peso: 4, categoria: "FISC" },
        { id: 34, codigo: "FISCEXEC34", atividade: "Execução direta - Montagem ou atualização de quadro de comando de sistema de automação (média complexidade)", peso: 8, categoria: "FISC" },
        { id: 35, codigo: "FISCEXEC35", atividade: "Execução direta - Montagem ou atualização de quadro de comando de sistema de automação (alta complexidade)", peso: 20, categoria: "FISC" },
        { id: 36, codigo: "FISCEXEC36", atividade: "Execução direta - Atualização de configurações de equipamento de automação predial, com parecer técnico (baixa complexidade)", peso: 4, categoria: "FISC" },
        { id: 37, codigo: "FISCEXEC37", atividade: "Execução direta - Atualização de configurações de equipamento de automação predial, com parecer técnico (média complexidade)", peso: 8, categoria: "FISC" },
        { id: 38, codigo: "FISCEXEC38", atividade: "Execução direta - Atualização de configurações de equipamento de automação predial, com parecer técnico (alta complexidade)", peso: 20, categoria: "FISC" },
        { id: 39, codigo: "FISCEXEC39", atividade: "Execução direta - Desenvolvimento ou atualização de programa de automação predial (baixa complexidade)", peso: 4, categoria: "FISC" },
        { id: 40, codigo: "FISCEXEC40", atividade: "Execução direta - Desenvolvimento ou atualização de programa de automação predial (média complexidade)", peso: 8, categoria: "FISC" },
        { id: 41, codigo: "FISCEXEC41", atividade: "Execução direta - Desenvolvimento ou atualização de programa de automação predial (alta complexidade)", peso: 20, categoria: "FISC" }
    ],
};
// ========== PRODUTOS (persistidos no DataStore) ==========
const MOCK_PRODUTOS_INICIAIS = []

// ========== MOCK API ==========
class MockAPI {
    static delay(ms = 50) { return new Promise(r => setTimeout(r, ms)); }

    static async getFeriados() {
        await this.delay();
        return { success: true, data: MOCK_FERIADOS };
    }
}

const MOCK_FERIADOS = [
    { id: 1,  data: '2025-01-01', nome: 'Ano Novo',                    tipo: 'nacional' },
    { id: 2,  data: '2025-03-03', nome: 'Carnaval',                    tipo: 'ponto-facultativo' },
    { id: 3,  data: '2025-03-04', nome: 'Carnaval',                    tipo: 'ponto-facultativo' },
    { id: 4,  data: '2025-04-18', nome: 'Sexta-feira Santa',           tipo: 'nacional' },
    { id: 5,  data: '2025-04-21', nome: 'Tiradentes',                  tipo: 'nacional' },
    { id: 6,  data: '2025-05-01', nome: 'Dia do Trabalho',             tipo: 'nacional' },
    { id: 7,  data: '2025-06-19', nome: 'Corpus Christi',              tipo: 'ponto-facultativo' },
    { id: 8,  data: '2025-09-07', nome: 'Independência do Brasil',     tipo: 'nacional' },
    { id: 9,  data: '2025-10-12', nome: 'Nossa Senhora Aparecida',     tipo: 'nacional' },
    { id: 10, data: '2025-11-02', nome: 'Finados',                     tipo: 'nacional' },
    { id: 11, data: '2025-11-15', nome: 'Proclamação da República',    tipo: 'nacional' },
    { id: 12, data: '2025-12-25', nome: 'Natal',                       tipo: 'nacional' },
    { id: 13, data: '2026-01-01', nome: 'Ano Novo',                    tipo: 'nacional' },
    { id: 14, data: '2026-02-16', nome: 'Carnaval',                    tipo: 'ponto-facultativo' },
    { id: 15, data: '2026-02-17', nome: 'Carnaval',                    tipo: 'ponto-facultativo' },
    { id: 16, data: '2026-04-03', nome: 'Sexta-feira Santa',           tipo: 'nacional' },
    { id: 17, data: '2026-04-21', nome: 'Tiradentes',                  tipo: 'nacional' },
    { id: 18, data: '2026-05-01', nome: 'Dia do Trabalho',             tipo: 'nacional' },
    { id: 19, data: '2026-06-04', nome: 'Corpus Christi',              tipo: 'ponto-facultativo' },
    { id: 20, data: '2026-09-07', nome: 'Independência do Brasil',     tipo: 'nacional' },
    { id: 21, data: '2026-10-12', nome: 'Nossa Senhora Aparecida',     tipo: 'nacional' },
    { id: 22, data: '2026-11-02', nome: 'Finados',                     tipo: 'nacional' },
    { id: 23, data: '2026-11-15', nome: 'Proclamação da República',    tipo: 'nacional' },
    { id: 24, data: '2026-12-25', nome: 'Natal',                       tipo: 'nacional' },
];

// ========== EXPORTAÇÕES ==========
window.MOCK_COLABORADORES       = MOCK_COLABORADORES;
window.MOCK_PRODUTOS_INICIAIS  = MOCK_PRODUTOS_INICIAIS;
window.MOCK_ATIVIDADES     = MOCK_ATIVIDADES;
window.MOCK_FERIADOS       = MOCK_FERIADOS;
window.CATEGORIAS          = CATEGORIAS;
window.BENCHMARK_AREA      = BENCHMARK_AREA;
window.AREA_CATEGORIAS     = AREA_CATEGORIAS;
window.CATEGORIA_PREFIX    = CATEGORIA_PREFIX;
window.COMPLEXIDADES       = COMPLEXIDADES;
window.MockAPI             = MockAPI;

// ========== PRESENÇA MOCK ==========
const MOCK_PRESENCA_INICIAL = {
    "presenca_1": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "14": "trabalhado",
                "15": "trabalhado",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "21": "trabalhado",
                "22": "trabalhado",
                "23": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "ausente",
                "30": "trabalhado"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "trabalhado",
                "04": "trabalhado",
                "05": "trabalhado",
                "06": "trabalhado",
                "09": "trabalhado",
                "10": "banco_horas",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "trabalhado",
                "25": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "trabalhado", "03": "trabalhado", "04": "trabalhado" }
},
    "presenca_2": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "14": "trabalhado",
                "15": "trabalhado",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "21": "trabalhado",
                "22": "trabalhado",
                "23": "trabalhado",
                "26": "ausente",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "trabalhado",
                "30": "trabalhado"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "trabalhado",
                "04": "trabalhado",
                "05": "trabalhado",
                "06": "trabalhado",
                "09": "trabalhado",
                "10": "trabalhado",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "trabalhado",
                "25": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "trabalhado", "03": "ausente",    "04": "trabalhado" }
},
    "presenca_3": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "14": "trabalhado",
                "15": "trabalhado",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "21": "trabalhado",
                "22": "trabalhado",
                "23": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "trabalhado",
                "30": "trabalhado"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "ausente",
                "04": "ausente",
                "05": "trabalhado",
                "06": "trabalhado",
                "09": "trabalhado",
                "10": "trabalhado",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "trabalhado",
                "25": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "trabalhado", "03": "trabalhado", "04": "trabalhado" }
},
    "presenca_4": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "14": "trabalhado",
                "15": "banco_horas",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "21": "trabalhado",
                "22": "trabalhado",
                "23": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "trabalhado",
                "30": "trabalhado"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "trabalhado",
                "04": "trabalhado",
                "05": "trabalhado",
                "06": "trabalhado",
                "09": "trabalhado",
                "10": "trabalhado",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "trabalhado",
                "25": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "banco_horas","03": "trabalhado", "04": "trabalhado" }
},
    "presenca_5": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "14": "trabalhado",
                "15": "trabalhado",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "21": "trabalhado",
                "22": "trabalhado",
                "23": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "trabalhado",
                "30": "trabalhado"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "trabalhado",
                "04": "trabalhado",
                "05": "trabalhado",
                "06": "trabalhado",
                "09": "trabalhado",
                "10": "trabalhado",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "ausente",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "trabalhado",
                "25": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "trabalhado", "03": "trabalhado", "04": "trabalhado" }
},
    "presenca_6": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "14": "trabalhado",
                "15": "trabalhado",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "21": "trabalhado",
                "22": "ausente",
                "23": "ausente",
                "26": "trabalhado",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "trabalhado",
                "30": "trabalhado"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "trabalhado",
                "04": "trabalhado",
                "05": "trabalhado",
                "06": "trabalhado",
                "09": "trabalhado",
                "10": "trabalhado",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "trabalhado",
                "25": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "trabalhado", "03": "trabalhado", "04": "ausente"    }
},
    "presenca_7": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "14": "trabalhado",
                "15": "trabalhado",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "21": "trabalhado",
                "22": "trabalhado",
                "23": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "trabalhado",
                "30": "banco_horas"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "trabalhado",
                "04": "trabalhado",
                "05": "trabalhado",
                "06": "trabalhado",
                "09": "trabalhado",
                "10": "trabalhado",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "ausente",
                "25": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "trabalhado", "03": "trabalhado", "04": "trabalhado" }
},
    "presenca_8": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "14": "trabalhado",
                "15": "trabalhado",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "21": "trabalhado",
                "22": "trabalhado",
                "23": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "ausente",
                "30": "banco_horas"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "trabalhado",
                "04": "trabalhado",
                "05": "trabalhado",
                "06": "trabalhado",
                "09": "trabalhado",
                "10": "trabalhado",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "trabalhado",
                "25": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "trabalhado", "03": "trabalhado", "04": "trabalhado" }
},
    "presenca_9": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "14": "trabalhado",
                "15": "trabalhado",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "21": "trabalhado",
                "22": "trabalhado",
                "23": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "trabalhado",
                "30": "trabalhado"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "trabalhado",
                "04": "trabalhado",
                "05": "trabalhado",
                "06": "ausente",
                "09": "trabalhado",
                "10": "trabalhado",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "trabalhado",
                "25": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "trabalhado", "03": "ausente",    "04": "trabalhado" }
},
    "presenca_10": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "14": "trabalhado",
                "15": "trabalhado",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "banco_horas",
                "21": "trabalhado",
                "22": "trabalhado",
                "23": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "trabalhado",
                "30": "trabalhado"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "trabalhado",
                "04": "trabalhado",
                "05": "trabalhado",
                "06": "trabalhado",
                "09": "trabalhado",
                "10": "trabalhado",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "trabalhado",
                "25": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "trabalhado", "03": "trabalhado", "04": "trabalhado" }
},
    "presenca_11": {
        "2026-01": {
                "05": "trabalhado",
                "06": "trabalhado",
                "07": "trabalhado",
                "08": "trabalhado",
                "09": "trabalhado",
                "12": "trabalhado",
                "13": "ausente",
                "14": "trabalhado",
                "15": "trabalhado",
                "16": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "21": "trabalhado",
                "22": "trabalhado",
                "23": "trabalhado",
                "26": "trabalhado",
                "27": "trabalhado",
                "28": "trabalhado",
                "29": "trabalhado",
                "30": "trabalhado"
        },
        "2026-02": {
                "02": "trabalhado",
                "03": "trabalhado",
                "04": "trabalhado",
                "05": "trabalhado",
                "06": "trabalhado",
                "09": "trabalhado",
                "10": "trabalhado",
                "11": "trabalhado",
                "12": "trabalhado",
                "13": "trabalhado",
                "18": "trabalhado",
                "19": "trabalhado",
                "20": "trabalhado",
                "23": "trabalhado",
                "24": "trabalhado",
                "25": "ausente",
                "26": "trabalhado",
                "27": "trabalhado"
        },
        "2026-03": { "02": "trabalhado", "03": "trabalhado", "04": "trabalhado" }
}
};

function initializeMockPresenca() {
    // Só inicializar presença se o servidor ainda não tem dados
    for (const key in MOCK_PRESENCA_INICIAL) {
        if (!DataStore.get(key)) {
            DataStore.set(key, MOCK_PRESENCA_INICIAL[key]);
        }
    }
    // Garantir produtos iniciais (storage.js já inicializa, mas por segurança)
    if (!DataStore.get("produtos_todos")) {
        DataStore.set("produtos_todos", MOCK_PRODUTOS_INICIAIS);
    }
}

if (typeof DataStore !== "undefined") {
    setTimeout(initializeMockPresenca, 150);
} else {
    document.addEventListener("DOMContentLoaded", () => setTimeout(initializeMockPresenca, 300));
}
